### ISSUE TITLE
Project Overview

### ISSUE THREAD

**Issue by ellen-li** [ellen-li/presto-card#1]
## Milestones

- [ ] IA and wireframing
- [ ] Define branding/style
- [ ] Front-end development of `widget`
- [ ] Front-end development of `add account`
- [ ] Front-end development of `balance`
- [ ] Front-end development of `settings`
- [ ] Connect to PRESTO website from app
- [ ] Get balance from PRESTO
- [ ] Fetch updated balance on every app or `widget` load
- [ ] Use camera to get card number
- [ ] Handling of wrong/updated password
- [ ] Privacy policy? Terms of use?

## Known constraints

- Newly purchased cards are not supported; returns N/A
- To be supported, card must be registered online with a transaction made within 7 days
- Need to track cookies, and respect redirects. In response to POST, cookies are sent in response, and a GET redirect is issued
- To get balance, do a POST to https://www.prestocard.ca/Home/Index with anonymous or registered parameters

```
anonymousLogin : 17-digit card ID
submitAccount_SubmitAnonymousLogin : "Log in"

registeredLogin: 17-digit card ID
password: 4-digit PIN
submitAccount_SubmitRegisteredLogin : "Log in" 
```

## Similar apps

- PRESTO Lookup ([Android](https://play.google.com/store/apps/details?id=org.bitbucket.efung.prestoreader))
- Transsistant for PRESTO ([Android](https://play.google.com/store/apps/details?id=com.idemfactor.android.presto), [iOS](https://itunes.apple.com/ca/app/transsistant-for-presto-card/id462502074?mt=8))
- Pronto ([iOS](https://itunes.apple.com/us/app/pronto-balance-checker-for/id1067148752?mt=8))
